apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aap-mcp-server

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - secret-template.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

commonLabels:
  app: aap-mcp-server

