apiVersion: v1
kind: Secret
metadata:
  name: aap-mcp-secrets
  namespace: aap-mcp-server
  labels:
    app: aap-mcp-server
type: Opaque
stringData:
  bearer-token: "YOUR_AAP_TOKEN_HERE"
  # Note: Replace YOUR_AAP_TOKEN_HERE with your actual AAP authentication token
  # You can create this secret using:
  # oc create secret generic aap-mcp-secrets --from-literal=bearer-token='your-token-here' -n aap-mcp-server
  # Or using the OpenShift web console

